### ISSUE TITLE
Problems setting up on OSX

### ISSUE THREAD

**Issue by ARolek** [omniscale/go-mapnik#3]
I'm having an issue getting this setup on OSX. My commands:

```
brew install mapnik --with-gdal --with-postgresql
go get github.com/omniscale/go-mapnik
```

which results in the following error:

```
../../go/src/github.com/omniscale/go-mapnik/mapnik_c_api.cpp:4:10: fatal error: 'mapnik/debug.hpp' file not found
```

brew is installing mapnik 3.0.5. Any ideas?

**Comment by ARolek** [comment]
I finally figured this out. When calling:

`go get github.com/omniscale/go-mapnik`

the package looks for the mapnik header files, but the local environment is not setup until you run:

`go generate github.com/omniscale/go-mapnik`

The following steps avoid the errors in the console (mapnik needs to be installed):

```
go get -d github.com/omniscale/go-mapnik
go generate github.com/omniscale/go-mapnik
go install github.com/omniscale/go-mapnik
```

the `-d` flag on `go get` cause the package to only be downloaded, not installed. Then the environment can be setup with `go generate` and then `go install` will work without errors.

I'm not going to send a pull request as it's up to you if you think expanding the Readme would be helpful for others.

**Comment by olt** [comment]
> I'm not going to send a pull request as it's up to you if you think expanding the Readme would be helpful for others. 

Please do! I didn't know about the `-d` option.

**Comment by ARolek** [comment]
Done. I actually was not familiar with it either until this weekend. I was trying to Dockerize Mapnik with go-mapnik but the compiler errors were getting in the way of the container successfully building. I have not tested the install on OSX and Ubuntu and they work great.

**Comment by olt** [comment]
Thanks!
